### ISSUE TITLE
NF_WriteText: "\n" doesn't do a newline and instead does a space.

### ISSUE THREAD

**Issue by ghost** [knightfox75/nds_nflib#10]
![image](https://github.com/knightfox75/nds_nflib/assets/172942173/062c3c59-5d51-4f2c-b640-c37b8f901d27)
This is the textdemo example from the repository, not a single change to the source code, using NFlib with BlocksDS, the latest binaries from wf-pacman, I also tried with devkitARM and older NFlib (the one from SourceForge) it was the same result. (https://github.com/knightfox75/nds_nflib/blob/master/examples/text/textdemo/source/main.c#L65)

**Comment by ghost** [comment]
#14 fixes this up

**Comment by AntonioND** [comment]
Thanks!
