### ISSUE TITLE
NFlib 1.1.3 version string is "1.1.1"

### ISSUE THREAD

**Issue by ghost** [knightfox75/nds_nflib#11]
https://github.com/knightfox75/nds_nflib/blob/master/include/nf_lib.h#L42

When making the previous issue I couldn't identify my NFlib version thanks to this. 

This isn't important but I would like for it to get fixed. I could make a pull request but I have no idea how this works if I'm being honest.

**Comment by AntonioND** [comment]
Fixed here: https://github.com/knightfox75/nds_nflib/pull/12
